name = "resumeai"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2026-02-16"
compatibility_flags = ["nodejs_compat"]

[env.production]
compatibility_date = "2026-02-16"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
NODE_ENV = "production"

[[env.production.d1_databases]]
database_id = "f45c484f-8178-409b-9b91-70fdee561767"
binding = "DB"
database_name = "DB"
